name: Run Frontend Tests with Coverage

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Specify the Node.js version you need

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run tests with coverage
        working-directory: ./frontend
        run: npm run test -- --coverage --verbose --ci --passWithNoTests
