name: Unit Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Python 3.7.17
        uses: actions/setup-python@v1
        with:
          python-version: 3.7.17

      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          pip install -r requirements.txt
          echo "Python requirements installed"

      - name: Run tests
        working-directory: ./backend
        run: |
          python -m unittest test_api.py
